// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://sisnsawccgnsttbxnobm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpc25zYXdjY2duc3R0Ynhub2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3NDgxMTgsImV4cCI6MjA5ODMyNDExOH0.0y38nM3wiHih-Yqx5zpd0qBl5RO8biKoCo2PWk6zWHk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);